# Generated by Django 4.0.5 on 2022-07-02 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('note_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'note',
            },
        ),
    ]
